### ISSUE TITLE
The suitable/appropriate completion settings for scratch buffer.

### ISSUE THREAD

**Issue by hongyi-zhao** [company-mode/company-mode#1130]
Currently, I'm using the following company relevant settings:
```emacs-lisp
(use-package company
  :config
    (global-company-mode)
  :custom
  ;https://github.com/company-mode/company-mode/issues/14#issuecomment-290261406
  ; Do not downcase the returned candidates automatically
  (company-dabbrev-downcase nil) 
  ; Trigger completion immediately.
  (company-idle-delay 0) 
  (company-minimum-prefix-length 1)
  (company-tooltip-align-annotations t)
  (company-dabbrev-other-buffers t) ; search buffers with the same major mode
  (company-selection-wrap-around t)
  ; Number the candidates (use M-1, M-2 etc to select completions).
  (company-show-numbers t)
    :bind (:map company-active-map
                ("C-n" . company-select-next)
                ("C-p" . company-select-previous)
                ("C-s" . company-filter-candidates)
                ("<tab>" . company-complete-selection))
    :bind (:map company-search-map
                ("C-n" . company-select-next)
                ("C-p" . company-select-previous)))

(use-package company-tabnine)
(setq company-backends
      '(
        ;https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Spell-check.html
        ;sudo apt-get install aspell
        ;`M-x describe-variable ispell-program-name RET`
        ;Its value is "/usr/bin/aspell"
        (company-tabnine :separate company-dabbrev company-keywords company-files company-ispell company-capf)
        ))

;; Add yasnippet support for all company backends.
(defvar company-mode/enable-yas t
  "Enable yasnippet for all backends.")

(defun company-mode/backend-with-yas (backend)
  (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
      backend
    (append (if (consp backend) backend (list backend))
            '(:with company-yasnippet))))

(setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))

;; Remove duplicate candidate.
(add-to-list 'company-transformers #'delete-dups)
```
This will cause the scratch buffer to be affected by the following completed configuration, as shown by `M-x company-diag RET` when I'm on this buffer: 

```emacs-lisp
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2021-06-19 on X10DAi
Company 0.9.13

company-backends: (company-math-symbols-unicode
 (company-tabnine :separate company-dabbrev company-keywords company-files company-ispell company-capf :with company-yasnippet))

Used backend: (company-tabnine :separate company-dabbrev company-keywords company-files company-ispell company-capf :with company-yasnippet)

Value of c-a-p-f: (elisp-completion-at-point t)
Major mode: lisp-interaction-mode
Prefix: ""
Completions:
[...]
```
It doesn't seem reasonable and convenient for using scratch buffer under this configuration. Any suggestions/revisions/adjustments will be highly appreciated.

Regards,
HY

**Comment by dgutov** [comment]
Why not just use `company-capf`?

**Comment by hongyi-zhao** [comment]
How to achieve this purpose?

**Comment by yugaego** [comment]
1. You could start with testing if a particular backend works for you in a particular situation.
  - For example: use command `M-x company-capf`  or `M-x company-begin-backend` (which will ask a backend's name).
2. After that the - supposedly - simplest approach would be to enable a backend(s) per some mode(s) via the usage of the hooks.
  - For example:
``` elisp
(add-hook 'emacs-lisp-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends)
              '(company-capf))))
```

I'm not aware of a hook that would work for the *scratch* buffer only. But taking into notice it's a buffer with `emacs-lisp-mode` major mode enabled, the example might work for your use case.

**Comment by dgutov** [comment]
> I'm not aware of a hook that would work for the scratch buffer only. But taking into notice it's a buffer with emacs-lisp-mode major mode enabled, the example might work for your use case.

By default it uses `lisp-interaction-mode` (which from `emacs-lisp-mode`), so `lisp-interactive-mode-hook` should work. Not sure if the OP wanted this behavior in scratch buffers *only*, though.

**Comment by hongyi-zhao** [comment]
I tried with the following code snippets in the `:config` section of the use-package setting for company, and then run `M-x company-diag RET` when I'm on scratch buffer, as shown below:
```emacs-lisp
        (add-hook 'emacs-lisp-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends)
              '(company-capf))))
```
![image](https://user-images.githubusercontent.com/11155854/125718959-47149e49-949c-4fde-a781-3db2ac68b643.png)

```emacs-lisp
        (add-hook 'lisp-interactive-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends)
              '(company-capf))))     
```

![image](https://user-images.githubusercontent.com/11155854/125719133-07d7e7af-4a49-4903-a7e4-abf62aa80fd7.png)

So, it seems that the `emacs-lisp-mode-hook` does the trick, while `lisp-interactive-mode-hook` doesn't.

**Comment by yugaego** [comment]
@dgutov
> By default it uses lisp-interaction-mode

 Hi Dmitry, thank you for the correction. I was confused by having `lisp-interaction-mode` defined in `elisp-mode.el`, but with only `emacs-lisp-mode-hook` hook defined in that file. [`lisp-interaction-mode-hook` resides in `lisp-mode.el`]
I'll update my comment accordingly.

**Comment by yugaego** [comment]
@hongyi-zhao

> So, it seems that the emacs-lisp-mode-hook does the trick, while lisp-interactive-mode-hook doesn't.

I believe I saw this issue too, but only once, on the first evaluation of the configuration probably (with killing/creating the buffer). Now I cannot reproduce this issue anymore: the hook is added and called in both cases when I test it.
I'd check `C-h v lisp-interactive-mode-hook` output if encountered the issue again (in addition to the killing/creating the \*scratch\* buffer).

**Comment by hongyi-zhao** [comment]
> I'd check `C-h v lisp-interactive-mode-hook` output if encountered the issue again (in addition to the killing/creating the *scratch* buffer).

See below:
```
lisp-interaction-mode-hook is a variable defined in elisp-mode.el.gz.

Value
nil
```

**Comment by dgutov** [comment]
It actually doesn't matter whether the variable is defined (and where).

`add-hook` creates the variable if it didn't exist before, and the major mode function (when defined with `define-derived-mode`) likewise runs the hook if it's defined and silently skips it if it does not.

**Comment by dgutov** [comment]
> So, it seems that the emacs-lisp-mode-hook does the trick, while lisp-interactive-mode-hook doesn't.

Perhaps your *scratch* is in `emacs-lisp-mode` and not in `lisp-interaction-mode` due to some prior configuration?

**Comment by hongyi-zhao** [comment]
I tried with the following configuration:
```emacs-lisp
;$ emacs -q --load ~/.emacs.d/init.company-capf-scratch

;;Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package company
  :demand t
  :hook
  (after-init . global-company-mode)
  :config
  (add-hook 'lisp-interactive-mode-hook
     (lambda ()
        (set (make-local-variable 'company-backends)
        '(company-capf))))   

```
Then I run `C-h v RET company-backends RET` in scratch buffer, and obtain the following result:

![image](https://user-images.githubusercontent.com/11155854/125795768-e7d00026-3583-421e-a92c-5ee8f1575e7f.png)

**Comment by dgutov** [comment]
What does `C-h v RET major-mode RET` say in *scratch*?

**Comment by hongyi-zhao** [comment]
See below:

![image](https://user-images.githubusercontent.com/11155854/125796929-882b7000-9963-4f12-9631-e5a1e1030854.png)

**Comment by dgutov** [comment]
Inside the buffer, after Emacs has already started, you can evaluate with `M-:`:

```
 (set (make-local-variable 'company-backends)
        '(company-capf))
```

**Comment by dgutov** [comment]
Or, even shorter:

```el
(setq-local company-backends '(company-capf))
```

**Comment by dgutov** [comment]
If the suggested configuration doesn't work, try dropping all the `straight` and `use-package` stuff and start with the basics.

**Comment by hongyi-zhao** [comment]
`$ emacs -Q`

Then use `M-:` to evaluate ` (setq-local company-backends '(company-capf))`  inside the scratch buffer. 

![image](https://user-images.githubusercontent.com/11155854/125800424-d68640b5-7faa-4ada-81b6-76cf98dc08dc.png)

**Comment by dgutov** [comment]
You should probably load and set up `company` as well.

**Comment by hongyi-zhao** [comment]
1. Start Emacs with the following init file:
```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```
2. `M-x package-install RET company RET`
3. `M-x global-company-mode RET`
4. Use `M-:` to evaluate ` (setq-local company-backends '(company-capf))`  inside the scratch buffer. 
5. `C-h v RET company-backends RET`.

![image](https://user-images.githubusercontent.com/11155854/125805140-df16a8ea-3ceb-4f4d-9f9f-49ccbf7afa91.png)

**Comment by dgutov** [comment]
> Value of c-a-p-f: (tags-completion-at-point-function)

This looks odd: it should have the buffer-local value associated with emacs-lisp-mode. That is, `(elisp-completion-at-point t)`.

**Comment by hongyi-zhao** [comment]
What's the possible reason and how to further analysis this problem?

**Comment by dgutov** [comment]
Maybe you have a `early-init.el` file?

Do you start Emacs with `emacs -Q` at the beginning of the scenario?

To debug, start `emacs -Q`, check the value of `completion-at-point-functions` in *scratch*. It should have the expected value.

Then evaluate your init script step by step (with `C-x C-x`) and see what changes, and at what step stuff breaks.

**Comment by hongyi-zhao** [comment]
> Maybe you have an `early-init.el` file inside `emacs.d`?

No.
 
> Do you start Emacs with `emacs -Q` at the beginning of the scenario?

I'm using `emacs -q --load ~/.emacs.d/init.company-capf-scratch`, with the following content in `~/.emacs.d/init.company-capf-scratch`:

```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```
 
> To debug, start `emacs -Q`, check the value of `completion-at-point-functions` in _scratch_. It should have the expected value.

![image](https://user-images.githubusercontent.com/11155854/125871215-a3547b43-4e64-4be8-9f86-4d59c3221071.png)

> Then evaluate your init script step by step (with `C-x C-x`) and see what changes, and at what step stuff breaks.

Do you mean paste/input the content of the init script in scratch buffer and then `C-x C-x` on it?

**Comment by dgutov** [comment]
The local value on the screenshot is about right.

> Do you mean paste/input the content of the init script in scratch buffer and then run C-x C-x on it?

More or less. You could also visit the file, and then `C-x C-e` after each top-level Lisp form, one after another. Or paste its contents, yes.

But see into the question I asked above first.

**Comment by hongyi-zhao** [comment]
But I found that on my side, `C-x C-x` doesn't bind to any eval relevant functions, as shown below:
 
![image](https://user-images.githubusercontent.com/11155854/125882504-1919b601-d9ae-49d8-8fa2-1d8070592f66.png)

**Comment by dgutov** [comment]
`C-x C-e`, not `C-x C-x`.

**Comment by hongyi-zhao** [comment]
Yes, `C-x C-x` does the trick:

![image](https://user-images.githubusercontent.com/11155854/125882814-91b74b0d-bd90-4cfc-a090-d4e0775dddc3.png)

**Comment by hongyi-zhao** [comment]
I tried with the following two methods, but either of them will set the company-backend to capf for `scratch` buffer: 

```emacs-lisp
;https://emacs.stackexchange.com/questions/34180/how-can-i-script-emacs-to-install-packages-from-list
;https://stackoverflow.com/questions/10092322/how-to-automatically-install-emacs-packages-by-specifying-a-list-of-package-name
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(setq package-selected-packages
      '(company
        async))
(package-install-selected-packages)


(unless package-archive-contents
  (package-refresh-contents))
(package-install-selected-packages t)

(global-company-mode)
(add-hook 'lisp-interaction-mode-hook
   (lambda ()
      (set (make-local-variable 'company-backends)
      '(company-capf))))
```

![image](https://user-images.githubusercontent.com/11155854/125960439-53a9b316-95eb-4328-8ba9-212d1c5b1d7a.png)

```emacs-lisp
;https://emacs.stackexchange.com/questions/34180/how-can-i-script-emacs-to-install-packages-from-list
;https://stackoverflow.com/questions/10092322/how-to-automatically-install-emacs-packages-by-specifying-a-list-of-package-name
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(setq package-selected-packages
      '(company
        async))
(package-install-selected-packages)


(unless package-archive-contents
  (package-refresh-contents))
(package-install-selected-packages t)

;(global-company-mode)
;(add-hook 'lisp-interaction-mode-hook
;   (lambda ()
;      (set (make-local-variable 'company-backends)
;      '(company-capf))))
      
(add-hook 'emacs-lisp-mode-hook
   (lambda ()
      (set (make-local-variable 'company-backends)
      '(company-capf))))         
```

![image](https://user-images.githubusercontent.com/11155854/125960868-b05b971c-812e-4ee7-ad91-224181e59ff2.png)

**Comment by yugaego** [comment]
Am I the only one who lost the thread of this discussion?

> but either of them will set the company-backend to capf for scratch buffer

@hongyi-zhao Did you mean "**n**either of them"? This would totally change the meaning.

If the point is to confirm the suggested configuration of a particular [backend for a major-mode](https://github.com/company-mode/company-mode/wiki/Tips-&-tricks#configure-different-backends-for-different-modes) works for the OP's \*scratch\* buffer, I suggest to confirm with this setup:

- Backup your current emacs configuration `~/.emacs.d`
- Create `~/.emacs.d/init.el` with this contents:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(package-install 'company)

(global-company-mode)

(defun my-lisp-interaction-mode-hook ()
  (setq-local company-backends '(company-capf)))

(add-hook 'lisp-interaction-mode-hook #'my-lisp-interaction-mode-hook)

```
- Launch fresh instance of Emacs.
- `C-x b <*scratch*> RET`
- Run `M-x company-diag` to expectedly see
```
Used backend: company-capf
Value of c-a-p-f: (elisp-completion-at-point t)
Major mode: lisp-interaction-mode
```

**Comment by hongyi-zhao** [comment]
> @hongyi-zhao Did you mean "neither of them"? This would totally change the meaning.

Yes. That's what I had wanted to say, and I've corrected this word in situ.

> If the point is to confirm the suggested configuration of a particular [backend for a major-mode](https://github.com/company-mode/company-mode/wiki/Tips-&-tricks#configure-different-backends-for-different-modes) works for the OP's *scratch* buffer, I suggest to confirm with this setup:

But, to be frank, I take the following inappropriate command to check the valid backend for a major-mode in the previous post, so I came to the wrong conclusion:

`C-h v company-backends RET`

The correct command for checking the backend settings for a major-mode should be the one you suggested above:

`M-x company-diag RET`

I reconfirm that all the following methods will set the backend for the *scratch* buffer to `capf`:


```emacs-lisp
(global-company-mode)

;;;
;(add-hook 'lisp-interaction-mode-hook
;   (lambda ()
;      (set (make-local-variable 'company-backends)
;      '(company-capf))))
   
;;or
      
;(add-hook 'emacs-lisp-mode-hook
;   (lambda ()
;      (set (make-local-variable 'company-backends)
;      '(company-capf))))      

;;or    

(defun my-lisp-interaction-mode-hook ()
  (setq-local company-backends '(company-capf)))

(add-hook 'lisp-interaction-mode-hook #'my-lisp-interaction-mode-hook)

```

**Comment by yugaego** [comment]
> I reconfirm that all the following methods will set the backend for the scratch buffer to capf

I'm glad you've got it working.

But let me to vindicate `C-h v company-backends RET`.
You should see a custom `company-backends` value similarly to the screenshots below
["Value '(company-ispell) ... Local in buffer TODO.org" in my use case.]

<img width="527" alt="company-backends-1" src="https://user-images.githubusercontent.com/296460/126761632-e7ccb46d-cf33-4532-bad5-2a01f87a9b72.png">
<img width="441" alt="company-backends-2" src="https://user-images.githubusercontent.com/296460/126761646-7e6f9ca7-4732-4d59-8213-aa4d8c1c5d5a.png">

**Comment by hongyi-zhao** [comment]
My observations are different from yours:

`C-h v company-backends RET`:

![image](https://user-images.githubusercontent.com/11155854/126762914-eceaf30b-e7ff-405a-878a-bf76469201b5.png)

`M-x company-diag RET`:

![image](https://user-images.githubusercontent.com/11155854/126762991-f02b2629-3a52-4cc2-9e3e-23ad498c3490.png)

**Comment by yugaego** [comment]
It looks like you still don't have **one** backend configured specifically for \*scratch\* buffer, but `company-capf` was selected from a bunch of the default backends. If that works for you - that's fine, you can leave it as it is. If you choose to troubleshoot, the instructions and hints were given above.

BTW, to quick-confirm, you can `M-x lisp-interaction-mode` while in \*scratch\* to re-init this major-mode and auto-call  `'my-lisp-interaction-mode-hook`   (or simply kill/create this buffer for the same result).

I **expect** you to see a picture closer to mine after that (if the rest was configured according to the approach suggested here).

**Comment by hongyi-zhao** [comment]
> It looks like you still don't have **one** backend configured specifically for *scratch* buffer, but `company-capf` was selected from a bunch of the default backends. If that works for you - that's fine, you can leave it as it is. If you choose to troubleshoot, the instructions and hints were given above.

At least in my product configuration, I don't meet troubles caused by the problem discussed here, so far.

> BTW, to quick-confirm, you can `M-x lisp-interaction-mode` while in *scratch* to re-init this major-mode and auto-call `'my-lisp-interaction-mode-hook` (or simply kill/create this buffer for the same result).
> 
> I **expect** you to see a picture closer to mine after that (if the rest was configured according to the approach suggested here).

Yes. See below:
`M-x lisp-interaction-mode RET`
`M-x describe-variable company-backends RET`
![image](https://user-images.githubusercontent.com/11155854/126770556-7db525c2-277c-47b4-b497-f4c43452da95.png)

**Comment by yugaego** [comment]
>  I don't meet troubles caused by the problem discussed here

Great!

> Yes. See below

Yep, that's it. Thank you for the confirmation.
Empty `C-h v lisp-interaction-mode-hook` value from the start signaled that you didn't have the hook assigned to the \*scratch\* buffer.

For a future *possible* reference, I'm also attaching a snippet that I alternatively used while playing around with the discussed question and investigating a question of a hook initialization for auto-created (default) \*scratch\* buffer.
```
(defun my-scratch-init ()
  (with-current-buffer "*scratch*"
     (setq-local company-backends '(company-capf))))

(add-hook 'emacs-startup-hook #'my-scratch-init)
```

**Comment by hongyi-zhao** [comment]
> Empty `C-h v lisp-interaction-mode-hook` value from the start signaled that you didn't have the hook assigned to the *scratch* buffer.

Non-nil, as shown below. This is the value seen immediately after I start Emacs with the suggested code snippet above, without run the following command:

`M-x lisp-interaction-mode RET`

![image](https://user-images.githubusercontent.com/11155854/126774753-8e2b0054-f690-47a8-8155-de6264279358.png)
 
> For a future _possible_ reference, I'm also attaching a snippet that I alternatively used while playing around with the discussed question and investigating a question of a hook initialization for auto-created (default) *scratch* buffer.
> 
> ```
> (defun my-scratch-init ()
>   (with-current-buffer "*scratch*"
>      (setq-local company-backends '(company-capf))))
> 
> (add-hook 'emacs-startup-hook #'my-scratch-init)
> ```

Wonderful, this does the trick without needing to rerun the following command:

`M-x lisp-interaction-mode RET`

But I still can't figure out the reason.

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out.
