### ISSUE TITLE
Overwriting value of ‘company-auto-complete’ by aliasing to ‘company-auto-commit’

### ISSUE THREAD

**Issue by OrionRandD** [company-mode/company-mode#1152]
How do I fix this annoying issue?
Warning (defvaralias): Overwriting value of ‘company-auto-complete’ by aliasing to ‘company-auto-commit’

**Comment by yugaego** [comment]
Renaming `company-auto-complete` to `company-auto-commit` in your configuration files should fix this warning.

Additional context:
`company-auto-complete` was renamed to `company-auto-commit` by commit d6df27f1 with [this reasoning](https://github.com/company-mode/company-mode/issues/1005#issuecomment-679419454).

In some cases, `Emacs` warns to [prevent losing value to defvaralias](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=5950).

**Comment by OrionRandD** [comment]
I have renamed that. But, now, my old config with "company-auto-complete"  does not work as it used to.
I had an auto-complete style of suggestions, instead of having a scrolling list defaulting company-mode.
Now I get this scroll list and I am not able to complete other languages, but only English  :(

Here is my config:


;; (setq company-format-margin-function #'company-vscode-light-icons-margin-function)

;; (defun company-ac-setup ()
;;   "Sets up `company-mode' to behave similarly to `auto-complete-mode'."
;;   (setq company-require-match nil)
;;   (setq company-auto-commit #'my-company-visible-and-explicit-action-p)
;;   (setq company-frontends '(company-echo-metadata-frontend
;;                             company-pseudo-tooltip-unless-just-one-frontend-with-delay
;;                             company-preview-frontend)))

;; (company-ac-setup)

;; (setq company-frontends
;;       '(company-pseudo-tooltip-unless-just-one-frontend
;;         company-preview-frontend
;;         company-echo-metadata-frontend))

(setq company-require-match 'never)

(setq company-auto-commit t)

(defun my-company-visible-and-explicit-action-p ()
  (and (company-tooltip-visible-p)
       (company-explicit-action-p)))

(defun company-ac-setup ()
  "Sets up `company-mode' to behave similarly to `auto-complete-mode'."
  (setq company-require-match nil)
  (setq company-auto-commit #'my-company-visible-and-explicit-action-p)
  (setq company-frontends '(company-echo-metadata-frontend
                            company-pseudo-tooltip-unless-just-one-frontend-with-delay
                            company-preview-frontend)))

(company-ac-setup)

**Comment by OrionRandD** [comment]
If this is not the right place to get help,
Could you point me to that?

**Comment by dgutov** [comment]
Let's try to resolve it here.

What do the commented-out and the not-commented-out sections of code represent? The "previous" config and the config required for the latest version of Company?

> But, now, my old config with "company-auto-complete" does not work as it used to.
I had an auto-complete style of suggestions, instead of having a scrolling list defaulting company-mode.

Try describing both the expected effect, and the actual result, in detail. Just like you would when filing a bug report.

**Comment by OrionRandD** [comment]
> Let's try to resolve it here.
> 
> What do the commented-out and the not-commented-out sections of code represent? The "previous" config and the config required for the latest version of Company?
> 
> > But, now, my old config with "company-auto-complete" does not work as it used to.
> > I had an auto-complete style of suggestions, instead of having a scrolling list defaulting company-mode.
> 
> Try describing both the expected effect, and the actual result, in detail. Just like you would when filing a bug report.

Now the code is updated...
I have deleted the commented part...
That is the setup not working...
I installed vertico and the completion is good, but still shows the scrolling list.
I would like the suggestions without the scroll list...

**Comment by yugaego** [comment]
Might be you'd get a better advice later, but meanwhile..
Your configuration reminded me of a similar one shown at #1116.
It used `(setq company-tooltip-idle-delay 10.0)` to postpone appearance of a tooltip.
(Assuming that by "scroll list" you meant a tooltip with the completion candidates.)

**Comment by dgutov** [comment]
@OrionRandD The above is definitely the variable to tweak. Did you set it to a different value before? The default of `.5` definitely isn't going to give you that effect.

Regarding the rest, please try some older version of Company (e.g. the latest release, you can install it from GNU ELPA or just download from Git) and see which of the behaviors are different. Then please mention the versions and describe the differences.

**Comment by yugaego** [comment]
Hi @OrionRandD , no response was given for several months, so I'm closing this ticket.
If you have additional questions regarding company setup, feel free to utilize [Discussions](https://github.com/company-mode/company-mode/discussions).
