### ISSUE TITLE
company-files can't complete common with punctuation characters

### ISSUE THREAD

**Issue by CeleritasCelery** [company-mode/company-mode#822]
when using company-files on a list of candidates that contain punctuation characters (i.e. `log.1`, `log.2`, etc. which contain the punctuation character `.`) calling `company-complete-common` (bound to `TAB`) results in company completing to the punctuation character then aborting. Modifying the syntax entry for the characters (in this case `.`) to the symbol class solves the problem, but that is not a workable solution.

**Comment by dgutov** [comment]
Thanks for the report.

It should probably be fixed in `company-files--regexps`, but I'm not sure what to do here exactly.

**Comment by CeleritasCelery** [comment]
I don't think this has to do with `company-files--regexps`. I can fix the problem by changing the syntax class of problematic characters, and `company-files--regexps` does not use any syntax classes in its regex.

I did a little experiment to prove that this is problem with `company-complete-common` for all backends.

1. create a new buffer in `emacs-lisp-mode`
2. eval `(modify-syntax-entry ?e ".")`. This makes the letter `e` a punctuation character
3. with `company-mode` enabled type `company-mo` and then press `TAB` (for `company-complete-common`)
4. notice that company will complete to the `e` and then abort

This leads me to believe that this is a problem with the way company is handling symbols. when it tries to resume after completing the common part it is looking back to see the symbol at point. But if the character is not a symbol it can't handle it. The reason we don't normally see it is because most backend's only have symbol characters in their candidates. That is not true for `company-files` which has to complete with characters like `.` which default to the punctuation class.

**Comment by dgutov** [comment]
Whether it looks for words, symbols or so on, depends on each particular backend.

**Comment by CeleritasCelery** [comment]
I still don't think this has to do with the backends. For example if you have a file `~/example.txt` and you write `~/example.`, then call `company-files` it will still complete on the dot, even though `.` is not a symbol. You can even call `company-files--grab-existing-name` and you can see that the prefix function does not care about syntax class at all (it will return `"~/.example."` even though that has a period). However when you try to complete common with a punctuation character it will cause company to abort. This should not happen, because the prefix is never `nil`. You can call `company-complete` to manually begin again, which means that backend is not the problem.

**Comment by dgutov** [comment]
OK, I've tried your initial scenario, and it works for me.

Do you have something non-default in your configuration?
