### ISSUE TITLE
Company completions very slow [company-jedi]

### ISSUE THREAD

**Issue by kirk86** [company-mode/company-mode#920]
Here's what I have in my config
```
(use-package comapny
  :ensure t
  :init (global-company-mode t)
  :config (setq company-idle-delay 0))

(use-package company-jedi
  :ensure t
  :init (add-to-list 'company-backends ' company-jedi)
  :config (setq jedi:complete-on-dot t))
```
The completions are extremely slow and never occur on dot. I have to type at least 3-4 chars and stop and wait a sec or two until completions starting showing up.

How can we speed things up?

**Comment by dgutov** [comment]
`M-x company-diag`?

**Comment by dgutov** [comment]
Anyway, if you're using `company-jedi`, it's a question for its maintainer.

**Comment by kirk86** [comment]
`M-x company-diag`

```
Emacs 26.3 (x86_64-apple-darwin18.6.0) of 2019-08-31 on Mojave.local
Company 0.9.10

company-backends: (company-jedi company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-jedi
Major mode: python-mode
Prefix: (#("rand" 0 4
   (fontified t))
 . t)

Completions:
  #("rand" 0 1 (:doc "rand(d0, d1, ..., dn, /)

rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `numpy.random.random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random" :symbol "f" :description "def rand")) "[f]"
  #("randint" 0 1 (:doc "randint(low, high=None, size=None, dtype='l', /)

randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the \"discrete uniform\" distribution of
the specified dtype in the \"half-open\" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int', etc, so byteorder is not available
    and a specific precision may have different C types depending
    on the platform. The default value is 'np.int'.

    .. versionadded:: 1.11.0

Returns
-------
out : int or ndarray of ints
    `size`-shaped array of random integers from the appropriate
    distribution, or a single such random int if `size` not provided.

See Also
--------
random.random_integers : similar to `randint`, only for the closed
    interval [`low`, `high`], and 1 is the lowest value if `high` is
    omitted.

Examples
--------
>>> np.random.randint(2, size=10)
array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0]) # random
>>> np.random.randint(1, size=10)
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generate a 2 x 4 array of ints between 0 and 4, inclusive:

>>> np.random.randint(5, size=(2, 4))
array([[4, 0, 2, 1], # random
       [3, 2, 2, 0]])

Generate a 1 x 3 array with 3 different upper bounds

>>> np.random.randint(1, [3, 5, 10])
array([2, 2, 9]) # random

Generate a 1 by 3 array with 3 different lower bounds

>>> np.random.randint([1, 5, 7], 10)
array([9, 8, 7]) # random

Generate a 2 by 4 array using broadcasting with dtype of uint8

>>> np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
array([[ 8,  6,  9,  7], # random
       [ 1, 16,  9, 12]], dtype=uint8)" :symbol "f" :description "def randint")) "[f]"
  #("randn" 0 1 (:doc "randn(d0, d1, ..., dn, /)

randn(d0, d1, ..., dn)

Return a sample (or samples) from the \"standard normal\" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `numpy.random.standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate \"normal\" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
Z : ndarray or float
    A ``(d0, d1, ..., dn)``-shaped array of floating-point samples from
    the standard normal distribution, or a single such float if
    no parameters were supplied.

See Also
--------
standard_normal : Similar, but takes a tuple as its argument.
normal : Also accepts mu and sigma arguments.

Notes
-----
For random samples from :math:`N(\\mu, \\sigma^2)`, use:

``sigma * np.random.randn(...) + mu``

Examples
--------
>>> np.random.randn()
2.1923875335537315  # random

Two-by-four array of samples from N(3, 6.25):

>>> 3 + 2.5 * np.random.randn(2, 4)
array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677],   # random
       [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])  # random" :symbol "f" :description "def randn")) "[f]"
  #("random" 0 1 (:doc "random(size=None, /)

random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API." :symbol "f" :description "def random")) "[f]"
  #("random_integers" 0 1 (:doc "random_integers(low, high=None, size=None, /)

random_integers(low, high=None, size=None)

Random integers of type np.int between `low` and `high`, inclusive.

Return random integers of type np.int from the \"discrete uniform\"
distribution in the closed interval [`low`, `high`].  If `high` is
None (the default), then results are from [1, `low`]. The np.int
type translates to the C long integer type and its precision
is platform dependent.

This function has been deprecated. Use randint instead.

.. deprecated:: 1.11.0

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is the *highest* such
    integer).
high : int, optional
    If provided, the largest (signed) integer to be drawn from the
    distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.

Returns
-------
out : int or ndarray of ints
    `size`-shaped array of random integers from the appropriate
    distribution, or a single such random int if `size` not provided.

See Also
--------
randint : Similar to `random_integers`, only for the half-open
    interval [`low`, `high`), and 0 is the lowest value if `high` is
    omitted.

Notes
-----
To sample from N evenly spaced floating-point numbers between a and b,
use::

  a + (b - a) * (np.random.random_integers(N) - 1) / (N - 1.)

Examples
--------
>>> np.random.random_integers(5)
4 # random
>>> type(np.random.random_integers(5))
<class 'numpy.int64'>
>>> np.random.random_integers(5, size=(3,2))
array([[5, 4], # random
       [3, 3],
       [4, 5]])

Choose five random numbers from the set of five evenly-spaced
numbers between 0 and 2.5, inclusive (*i.e.*, from the set
:math:`{0, 5/8, 10/8, 15/8, 20/8}`):

>>> 2.5 * (np.random.random_integers(5, size=(5,)) - 1) / 4.
array([ 0.625,  1.25 ,  0.625,  0.625,  2.5  ]) # random

Roll two six sided dice 1000 times and sum the results:

>>> d1 = np.random.random_integers(1, 6, 1000)
>>> d2 = np.random.random_integers(1, 6, 1000)
>>> dsums = d1 + d2

Display results as a histogram:

>>> import matplotlib.pyplot as plt
>>> count, bins, ignored = plt.hist(dsums, 11, density=True)
>>> plt.show()" :symbol "f" :description "def random_integers")) "[f]"
  #("random_sample" 0 1 (:doc "random_sample(size=None, /)

random_sample(size=None)

Return random floats in the half-open interval [0.0, 1.0).

Results are from the \"continuous uniform\" distribution over the
stated interval.  To sample :math:`Unif[a, b), b > a` multiply
the output of `random_sample` by `(b-a)` and add `a`::

  (b - a) * random_sample() + a

Parameters
----------
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.

Returns
-------
out : float or ndarray of floats
    Array of random floats of shape `size` (unless ``size=None``, in which
    case a single float is returned).

Examples
--------
>>> np.random.random_sample()
0.47108547995356098 # random
>>> type(np.random.random_sample())
<class 'float'>
>>> np.random.random_sample((5,))
array([ 0.30220482,  0.86820401,  0.1654503 ,  0.11659149,  0.54323428]) # random

Three-by-two array of random numbers from [-5, 0):

>>> 5 * np.random.random_sample((3, 2)) - 5
array([[-3.99149989, -0.52338984], # random
       [-2.99091858, -0.79479508],
       [-1.23204345, -1.75224494]])" :symbol "f" :description "def random_sample")) "[f]"
  #("RandomState" 0 1 (:doc "RandomState(seed=None, /)

RandomState(seed=None)

Container for the slow Mersenne Twister pseudo-random number generator.
Consider using a different BitGenerator with the Generator container
instead.

`RandomState` and `Generator` expose a number of methods for generating
random numbers drawn from a variety of probability distributions. In
addition to the distribution-specific arguments, each method takes a
keyword argument `size` that defaults to ``None``. If `size` is ``None``,
then a single value is generated and returned. If `size` is an integer,
then a 1-D array filled with generated values is returned. If `size` is a
tuple, then an array with that shape is filled and returned.

**Compatibility Guarantee**

A fixed bit generator using a fixed seed and a fixed series of calls to
'RandomState' methods using the same parameters will always produce the
same results up to roundoff error except when the values were incorrect.
`RandomState` is effectively frozen and will only receive updates that
are required by changes in the the internals of Numpy. More substantial
changes, including algorithmic improvements, are reserved for
`Generator`.

Parameters
----------
seed : {None, int, array_like, BitGenerator}, optional
    Random seed used to initialize the pseudo-random number generator or
    an instantized BitGenerator.  If an integer or array, used as a seed for
    the MT19937 BitGenerator. Values can be any integer between 0 and
    2**32 - 1 inclusive, an array (or other sequence) of such integers,
    or ``None`` (the default).  If `seed` is ``None``, then the `MT19937`
    BitGenerator is initialized by reading data from ``/dev/urandom``
    (or the Windows analogue) if available or seed from the clock
    otherwise.

Notes
-----
The Python stdlib module \"random\" also contains a Mersenne Twister
pseudo-random number generator with a number of methods that are similar
to the ones available in `RandomState`. `RandomState`, besides being
NumPy-aware, has the advantage that it provides a much larger number
of probability distributions to choose from.

See Also
--------
Generator
mt19937.MT19937
Bit_Generators" :symbol "c" :description "class RandomState")) "[c]"
```

**Comment by dgutov** [comment]
> Used backend: company-jedi

That is your answer.

**Comment by kirk86** [comment]
So you're saying that the problem is company-jedi? Well I've made aware both company-jedi and python jedi maintainers but I don't see this as being resolved at any time soon....

**Comment by dgutov** [comment]
I'm sorry to hear that, but `company-mode` itself contains no Python support code.

You could try an alternative backend with Python support, though. Like `company-anaconda` or `company-lsp` (both require installing corresponding bigger packages).

**Comment by mpfeifer** [comment]
@kirk86 It's eventually not what you had in mind, but from the description you gave you might want to play with configuration settings: company-idle-delay, company-minimum-prefix-length.

**Comment by kirk86** [comment]
@mpfeifer thanks Matthias, I'll give it a try!

**Comment by andschwa** [comment]
@kirk86 For what it's worth, I ran into similar issues with `company-anaconda`:

https://github.com/pythonic-emacs/company-anaconda/issues/34

Currently I'm using `lsp-mode` with the `pyls` server, and followed the former's instructions to use Emacs 27 with native JSON parsing. It's still not instantaneous but it is working fast enough for my needs.

**Comment by dgutov** [comment]
*If* JSON parsing is indeed the bottleneck, someone should look into integrating it into `anaconda-mode` (it isn't, as of now).
